# action.yml
# ------------------------------------------------------------------
# GitHub Action: Close PRs with Empty Descriptions
#
# This Action automatically closes pull requests that have
# an empty or whitespace-only description. It also posts a comment
# to notify the creator about the closure.
# ------------------------------------------------------------------

name: "Close PRs with Empty Descriptions"
author: "naveenkarasu"
description: "This GitHub Action automatically closes pull requests with an empty description, and posts a comment to notify the user."
branding:
  icon: "activity"
  color: "blue"

# Define any inputs your Action needs.
inputs:
  github-token:
    description: "GitHub token for authentication."
    required: true

# This tells GitHub how to run your Action.
runs:
  using: "composite"
  steps:
    - name: Close PRs without proper description
      # We use actions/github-script to interact with the GitHub API via JavaScript.
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          // Fetch all open pull requests using pagination.
          const prs = await github.paginate(github.rest.pulls.list, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: "open"
          });
          
          // If no open PRs are found, log a message and exit.
          if (!prs || prs.length === 0) {
            console.log("No open pull requests found.");
            return;
          }
          
          // Loop through each pull request.
          for (const pr of prs) {
            // Check if the pull request's description (body) is empty or only whitespace.
            if (!pr.body || pr.body.trim().length === 0) {
              // Determine the username if available; if not, use 'unknown user'.
              const username = pr.user && pr.user.login ? pr.user.login : "unknown user";
              console.log(`PR #${pr.number} by ${username} has an empty description.`);
              
              // If valid user info exists, post a comment to notify the PR creator.
              if (pr.user && pr.user.login) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: `@${pr.user.login}, your pull request has been closed because it does not include a description. Please update your PR with the necessary details and reopen it.`
                });
              } else {
                console.log(`PR #${pr.number} does not have valid user info; no comment will be posted.`);
              }
              
              // Close the pull request.
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                state: "closed"
              });
              
              console.log(`PR #${pr.number} closed.`);
            }
          }
